server:
  port: 8180

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth?connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver